services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=3000
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
